/* eslint-disable @typescript-eslint/no-unused-vars */
import Link from 'next/link';

import { buttonVariants } from '@/components/button';
import { Icons } from '@/components/icons';
import { cn } from '@/lib/utils';

export const links = [
  {
    name: 'Home',
    hash: '#home',
  },
  {
    name: 'About',
    hash: '#about',
  },
  {
    name: 'Experience',
    hash: '#experience',
  },
  {
    name: 'Projects',
    hash: '#projects',
  },
  {
    name: 'Motion Graphics',
    hash: '#motion-graphics',
  },
  {
    name: 'Contact',
    hash: '#contact',
  },
] as const;

export const projectsData = [
  {
    image: '/images/static/visa-cn.jpg',
    title: 'China Medical Visa',
    description: 'Social Media Posts Design for Chinese Visa from Bangladesh',
    category: 'Social Media Posts',
    technologies: ['Adobe Illustrator', 'Adobe'],
    links: {
      preview: 'https://tanvirvisuals.com',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/visa-malay.jpg',
    title: 'Malaysian Visa',
    description: 'Social Media Posts Design for Malaysian Visa from Bangladesh',
    category: 'Social Media Posts',
    technologies: ['Adobe Illustrator', 'Adobe'],
    links: {
      preview: 'https://tanvirvisuals.com',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/study-abroad.jpg',
    title: 'Study Abroad',
    description: 'Social Media Posts Design for Study Abroad from Bangladesh',
    category: 'Social Media Posts',
    technologies: ['Adobe Illustrator', 'Adobe'],
    links: {
      preview: 'https://tanvirvisuals.com',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/sys1.jpg',
    title: 'Product Promotion',
    description:
      'Social Media Posts Design for Product Promotion from Bangladesh',
    category: 'Marketing Ads',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/sys2.jpg',
    title: 'Product Promotion',
    description:
      'Social Media Posts Design for Product Promotion from Bangladesh',
    category: 'Marketing Ads',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/sys3.jpg',
    title: 'Product Promotion',
    description:
      'Social Media Posts Design for Product Promotion from Bangladesh',
    category: 'Marketing Ads',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/sys4.jpg',
    title: 'Product Promotion',
    description:
      'Social Media Posts Design for Product Promotion from Bangladesh',
    category: 'Marketing Ads',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/sys5.jpg',
    title: 'Product Promotion',
    description:
      'Social Media Posts Design for Product Promotion from Bangladesh',
    category: 'Marketing Ads',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/sys6.jpg',
    title: 'Product Promotion',
    description:
      'Social Media Posts Design for Product Promotion from Bangladesh',
    category: 'Marketing Ads',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/sys7.jpg',
    title: 'Product Promotion',
    description:
      'Social Media Posts Design for Product Promotion from Bangladesh',
    category: 'Marketing Ads',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/sys8.jpg',
    title: 'Product Promotion',
    description:
      'Social Media Posts Design for Product Promotion from Bangladesh',
    category: 'Marketing Ads',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/sys9.jpg',
    title: 'Product Promotion',
    description:
      'Social Media Posts Design for Product Promotion from Bangladesh',
    category: 'Marketing Ads',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/sys10.jpg',
    title: 'Product Promotion',
    description:
      'Social Media Posts Design for Product Promotion from Bangladesh',
    category: 'Marketing Ads',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/sys11.jpg',
    title: 'Product Promotion',
    description:
      'Social Media Posts Design for Product Promotion from Bangladesh',
    category: 'Marketing Ads',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/14dec.jpg',
    title: 'Occasional Greetings',
    description: 'Social Media Posts Design for Company Promotion',
    category: 'Marketing Ads',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/16dec.jpg',
    title: 'Occasional Greetings',
    description: 'Social Media Posts Design for Company Promotion',
    category: 'Marketing Ads',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/bank-accounts.jpg',
    title: 'Bank Account Details',
    description: 'Design for Bank Account Showcasing to Clients',
    category: 'Marketing Ads',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/blog-post.jpg',
    title: 'Blog Post Design',
    description:
      'Social Media Posts Design for Product Promotion from Bangladesh',
    category: 'Marketing Ads',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/blog-post2.jpg',
    title: 'Blog Post Design',
    description: 'Social Media Posts Design for Blog Promotion from Bangladesh',
    category: 'Marketing Ads',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/calender2026.jpg',
    title: 'Calendar Design of the Year 2026',
    description: 'Calendar Design for Company Promotion from Bangladesh',
    category: 'Branding',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/campaign.jpg',
    title: 'Campaign Design',
    description: 'Calendar Design for Company Promotion from Bangladesh',
    category: 'Social Media Posts',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/camp2.jpg',
    title: 'Campaign Design',
    description: 'Calendar Design for Company Promotion from Bangladesh',
    category: 'Social Media Posts',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/camp4.jpg',
    title: 'Campaign Design',
    description: 'Calendar Design for Company Promotion from Bangladesh',
    category: 'Social Media Posts',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/camp6.jpg',
    title: 'Campaign Design',
    description: 'Calendar Design for Company Promotion from Bangladesh',
    category: 'Social Media Posts',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/camp7.jpg',
    title: 'Campaign Design',
    description: 'Calendar Design for Company Promotion from Bangladesh',
    category: 'Social Media Posts',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/chillox-collab.jpg',
    title: 'Collaboration Campaign Design',
    description: 'Calendar Design for Company Promotion from Bangladesh',
    category: 'Branding',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/comtrade.jpg',
    title: 'Social Marketing Design',
    description: 'Calendar Design for Company Promotion from Bangladesh',
    category: 'Marketing Ads',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/comtrade2.jpg',
    title: 'Social Marketing Design',
    description: 'Calendar Design for Company Promotion from Bangladesh',
    category: 'Marketing Ads',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/comtrade3.jpg',
    title: 'Social Marketing Design',
    description: 'Calendar Design for Company Promotion from Bangladesh',
    category: 'Marketing Ads',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/comtrade4.jpg',
    title: 'Social Marketing Design',
    description: 'Calendar Design for Company Promotion from Bangladesh',
    category: 'Marketing Ads',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/comtrade5.jpg',
    title: 'Social Marketing Design',
    description: 'Calendar Design for Company Promotion from Bangladesh',
    category: 'Marketing Ads',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/comtrade6.jpg',
    title: 'Social Marketing Design',
    description: 'Calendar Design for Company Promotion from Bangladesh',
    category: 'Marketing Ads',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/comtrade7.jpg',
    title: 'Social Marketing Design',
    description: 'Calendar Design for Company Promotion from Bangladesh',
    category: 'Marketing Ads',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/comtrade8.jpg',
    title: 'Social Marketing Design',
    description: 'Calendar Design for Company Promotion from Bangladesh',
    category: 'Marketing Ads',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/comtrade9.jpg',
    title: 'Social Marketing Design',
    description: 'Calendar Design for Company Promotion from Bangladesh',
    category: 'Marketing Ads',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/comtrade10.jpg',
    title: 'Social Marketing Design',
    description: 'Calendar Design for Company Promotion from Bangladesh',
    category: 'Marketing Ads',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/comtrade11.jpg',
    title: 'Social Marketing Design',
    description: 'Calendar Design for Company Promotion from Bangladesh',
    category: 'Marketing Ads',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/active-force-branding.jpg',
    title: 'Social Marketing Design',
    description: 'Calendar Design for Company Promotion from Bangladesh',
    category: 'Branding',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/cristmasaf.jpg',
    title: 'Social Marketing Design',
    description: 'Calendar Design for Company Promotion from Bangladesh',
    category: 'Branding',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/cristmasaf2.jpg',
    title: 'Social Marketing Design',
    description: 'Calendar Design for Company Promotion from Bangladesh',
    category: 'Branding',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/eid-post1.jpg',
    title: 'Social Marketing Design',
    description: 'Calendar Design for Company Promotion from Bangladesh',
    category: 'Branding',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/eid-post2.jpg',
    title: 'Social Marketing Design',
    description: 'Calendar Design for Company Promotion from Bangladesh',
    category: 'Branding',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/eid-post3.jpg',
    title: 'Social Marketing Design',
    description: 'Calendar Design for Company Promotion from Bangladesh',
    category: 'Branding',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/eid-post4.jpg',
    title: 'Social Marketing Design',
    description: 'Calendar Design for Company Promotion from Bangladesh',
    category: 'Branding',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/eid-post5.jpg',
    title: 'Social Marketing Design',
    description: 'Calendar Design for Company Promotion from Bangladesh',
    category: 'Branding',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/logo1.jpg',
    title: 'Logo Design',
    description: 'Calendar Design for Company Promotion from Bangladesh',
    category: 'Branding',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/logo2.png',
    title: 'Logo Design',
    description: 'Calendar Design for Company Promotion from Bangladesh',
    category: 'Branding',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/logo3.png',
    title: 'Logo Design',
    description: 'Calendar Design for Company Promotion from Bangladesh',
    category: 'Branding',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/meetup-banner.jpg',
    title: 'Banner Design',
    description: 'Calendar Design for Company Promotion from Bangladesh',
    category: 'Branding',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/unify-eid.jpg',
    title: 'Occasional Social Design',
    description: 'Calendar Design for Company Promotion from Bangladesh',
    category: 'Social Media Posts',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/new-year1.jpg',
    title: 'Occasional Social Design',
    description: 'Calendar Design for Company Promotion from Bangladesh',
    category: 'Social Media Posts',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/new-year2.jpg',
    title: 'Occasional Social Design',
    description: 'Calendar Design for Company Promotion from Bangladesh',
    category: 'Social Media Posts',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/14decpost.jpg',
    title: 'Occasional Social Design',
    description: 'Calendar Design for Company Promotion from Bangladesh',
    category: 'Social Media Posts',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/tour2024.jpg',
    title: 'Social Media Design',
    description:
      'Social Media Post Design for Tour Company Promotion in Bangladesh',
    category: 'Social Media Posts',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/visa-cn.jpg',
    title: 'Social Media Design',
    description: 'Social Media Post Design for VISA Processing from Bangladesh',
    category: 'Social Media Posts',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/visa-malay.jpg',
    title: 'Social Media Design',
    description: 'Social Media Post Design for VISA Processing from Bangladesh',
    category: 'Social Media Posts',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/study-abroad.jpg',
    title: 'Social Media Post Design',
    description: 'Social Design for Study Abroad from Bangladesh',
    category: 'Social Media Posts',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/walkie-slider.jpg',
    title: 'Social Media Marketing Design',
    description: 'Social Media Post Design for Company Promotion',
    category: 'Social Media Posts',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/static/walkie-slider2.jpg',
    title: 'Social Media Marketing Design',
    description: 'Social Media Post Design for Company Promotion',
    category: 'Social Media Posts',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/print/invitation-card.jpg',
    title: 'Print Media Design',
    description: 'Print Media Design for Company Promotion',
    category: 'Print Media',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/print/sticker-UniPrashad.jpg',
    title: 'Print Media Design',
    description: 'Print Media Design for Company Promotion',
    category: 'Print Media',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    image: '/images/print/sticker-UniPrashad-5.jpg',
    title: 'Print Media Design',
    description: 'Print Media Design for Company Promotion',
    category: 'Print Media',
    technologies: ['Adobe Illustrator', 'Adobe Photoshop'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
] as const;

// ...existing code...

export const motionGraphicsData = [
  {
    video: 'motion/book-promo1.mp4',
    title: 'Book Promotional Motion',
    description: 'Book promotion animation for social media',
    category: 'Promo Animation',
    technologies: ['After Effects', 'Adobe Premiere Pro'],
    links: {
      preview: 'https://tanvirvisuals.com',
      github: '',
      githubApi: '',
    },
  },
  {
    video: 'motion/book-promo2.mp4',
    title: 'Book Promotional Motion Video',
    description: 'Book promotion animation for social media',
    category: 'Promo Animation',
    technologies: ['After Effects', 'Adobe Premiere Pro'],
    links: {
      preview: 'https://tanvirvisuals.com',
      github: '',
      githubApi: '',
    },
  },
  {
    video: 'motion/eye-logo-animation.mp4',
    title: 'Eye Logo Animation',
    description: 'Dynamic Logo animation',
    category: 'Logo Animation',
    technologies: ['After Effects', 'Adobe Premiere Pro'],
    links: {
      preview: 'https://tanvirvisuals.com',
      github: '',
      githubApi: '',
    },
  },
  {
    video: 'motion/fb-story.mp4',
    title: 'Facebook Promo Story',
    description: 'Facebook story promotion animation for social media',
    category: 'Promotional Ads',
    technologies: ['After Effects', 'Adobe Premiere Pro'],
    links: {
      preview: 'https://tanvirvisuals.com',
      github: '',
      githubApi: '',
    },
  },
  {
    video: 'motion/gaming-logo-animation.mp4',
    title: 'Gaming Logo Animation',
    description: 'Gaming logo animation video',
    category: 'Logo Animation',
    technologies: ['After Effects', 'Adobe Premiere Pro'],
    links: {
      preview: 'https://tanvirvisuals.com',
      github: '',
      githubApi: '',
    },
  },
  {
    video: 'motion/gif-banner.mp4',
    title: 'Gif Banner Animation',
    description: 'Company promotion animation for social media',
    category: 'Promotional Ads',
    technologies: ['After Effects', 'Adobe Premiere Pro'],
    links: {
      preview: 'https://tanvirvisuals.com',
      github: '',
      githubApi: '',
    },
  },
  {
    video: 'motion/gif-banner2.mp4',
    title: 'Gif Banner Animation',
    description: 'Company promotion animation for social media',
    category: 'Promotional Ads',
    technologies: ['After Effects', 'Adobe Premiere Pro'],
    links: {
      preview: 'https://tanvirvisuals.com',
      github: '',
      githubApi: '',
    },
  },
  {
    video: 'motion/intro1.mp4',
    title: 'Short Intro Animation',
    description: 'Short promotional animation for social media',
    category: 'Shorts/Reels',
    technologies: ['After Effects', 'Adobe Premiere Pro'],
    links: {
      preview: 'https://tanvirvisuals.com',
      github: '',
      githubApi: '',
    },
  },
  {
    video: 'motion/trailer.mp4',
    title: 'Short Intro Animation',
    description: 'Short promotional trailer video for social media',
    category: 'Shorts/Reels',
    technologies: ['After Effects', 'Adobe Premiere Pro'],
    links: {
      preview: 'https://tanvirvisuals.com',
      github: '',
      githubApi: '',
    },
  },
  {
    video: 'motion/kinetic-typography.mp4',
    title: 'Kinetic Typgrahpy Animation',
    description: 'Short promotional animation for social media',
    category: 'Video Editing',
    technologies: ['After Effects', 'Adobe Premiere Pro'],
    links: {
      preview: 'https://tanvirvisuals.com',
      github: '',
      githubApi: '',
    },
  },
  {
    video: 'motion/landscape-2.mp4',
    title: 'Landscape Animation',
    description: 'Short landscape promotional animation video',
    category: 'Promotional Ads',
    technologies: ['After Effects', 'Adobe Premiere Pro'],
    links: {
      preview: 'https://tanvirvisuals.com',
      github: '',
      githubApi: '',
    },
  },
  {
    video: 'motion/landscape-animation.mp4',
    title: 'Landscape Animation Video',
    description: 'Short landscape promotional animation video',
    category: 'Promotional Ads',
    technologies: ['After Effects', 'Adobe Premiere Pro'],
    links: {
      preview: 'https://tanvirvisuals.com',
      github: '',
      githubApi: '',
    },
  },
  {
    video: 'motion/lower-third.mp4',
    title: 'Lower Third Presentation Video',
    description: 'Short promotional lower third presentation for social media',
    category: 'Promotional Ads',
    technologies: ['After Effects', 'Adobe Premiere Pro'],
    links: {
      preview: 'https://tanvirvisuals.com',
      github: '',
      githubApi: '',
    },
  },
  {
    video: 'motion/lyrical-music-video.mp4',
    title: 'Lyrical Music Video Animation',
    description: 'Lyrical Music Video Animation',
    category: 'Video Editing',
    technologies: ['After Effects', 'Adobe Premiere Pro'],
    links: {
      preview: 'https://tanvirvisuals.com',
      github: '',
      githubApi: '',
    },
  },
  {
    video: 'motion/mobile-app-ui.mp4',
    title: 'Mobile Application UI Animation',
    description: 'Animation video for mobile app user experiences',
    category: 'Promotional Ads',
    technologies: ['After Effects', 'Adobe Premiere Pro'],
    links: {
      preview: 'https://tanvirvisuals.com',
      github: '',
      githubApi: '',
    },
  },
  {
    video: 'motion/motion-promo.mp4',
    title: 'Promotional Motion Animation',
    description: 'Promotional Motion Animation Video',
    category: 'Promotional Ads',
    technologies: ['After Effects', 'Adobe Premiere Pro'],
    links: {
      preview: 'https://tanvirvisuals.com',
      github: '',
      githubApi: '',
    },
  },
  {
    video: 'motion/pen-logo-animation.mp4',
    title: 'Creative Pen Logo Animation',
    description: 'Logo Promotional Animation Video',
    category: 'Logo Animation',
    technologies: ['After Effects', 'Adobe Premiere Pro'],
    links: {
      preview: 'https://tanvirvisuals.com',
      github: '',
      githubApi: '',
    },
  },
  {
    video: 'motion/pharmacy.mp4',
    title: 'Promotional Animation of a Pharmacy',
    description: 'Pharmacy Promotional Animation Video',
    category: 'Promotional Ads',
    technologies: ['After Effects', 'Adobe Premiere Pro'],
    links: {
      preview: 'https://tanvirvisuals.com',
      github: '',
      githubApi: '',
    },
  },
  {
    video: 'motion/product-promo1.mp4',
    title: 'Product Promotional Animation',
    description: 'Product Promotional Animation Video',
    category: 'Promotional Ads',
    technologies: ['After Effects', 'Adobe Premiere Pro'],
    links: {
      preview: 'https://tanvirvisuals.com',
      github: '',
      githubApi: '',
    },
  },
  {
    video: 'motion/story-2.mp4',
    title: 'Facebook Story Promotional Animation',
    description: 'Facebook Promotional Animation Story',
    category: 'Promotional Ads',
    technologies: ['After Effects', 'Adobe Premiere Pro'],
    links: {
      preview: 'https://tanvirvisuals.com',
      github: '',
      githubApi: '',
    },
  },
  {
    video: 'motion/editing/client-rev.mp4',
    title: 'Client Review',
    description: 'Client Testimonial for a security company',
    category: 'Video Editing',
    technologies: ['After Effects', 'Adobe Premiere Pro'],
    links: {
      preview: 'https://tanvirvisuals.com',
      github: '',
      githubApi: '',
    },
  },
  {
    video: 'motion/editing/client-rev2.mp4',
    title: 'Client Review',
    description: 'Client Testimonial for a security company',
    category: 'Video Editing',
    technologies: ['After Effects', 'Adobe Premiere Pro'],
    links: {
      preview: 'https://tanvirvisuals.com',
      github: '',
      githubApi: '',
    },
  },
  {
    video: 'editing/client-rev3.mp4',
    title: 'Client Review',
    description: 'Client Testimonial for a security company',
    category: 'Video Editing',
    technologies: ['After Effects', 'Adobe Premiere Pro'],
    links: {
      preview: 'https://tanvirvisuals.com',
      github: '',
      githubApi: '',
    },
  },
  {
    video: 'editing/promo-clip.mp4',
    title: 'Promotional Video Clip',
    description: 'Promotional filmy video',
    category: 'Video Editing',
    technologies: ['After Effects', 'Adobe Premiere Pro'],
    links: {
      preview: 'https://tanvirvisuals.com',
      github: '',
      githubApi: '',
    },
  },
  {
    video: 'editing/unifly-travels.mp4',
    title: 'Travel Agency Promotional Video',
    description: 'Travel Agency Promotional Video',
    category: 'Video Editing',
    technologies: ['After Effects', 'Adobe Premiere Pro'],
    links: {
      preview: 'https://tanvirvisuals.com',
      github: '',
      githubApi: '',
    },
  },
  {
    video: '/motion-1.mp4',
    title: 'Logo Promotion Animation',
    description: 'Dynamic product promotion animation for social media',
    category: 'Logo Animation',
    technologies: ['After Effects', 'Adobe Premiere Pro'],
    links: {
      preview: 'https://tanvirvisuals.com',
      github: '',
      githubApi: '',
    },
  },
  {
    video: '/motion-2.mp4',
    title: 'Brand Intro Animation',
    description: 'Animated brand introduction with modern effects',
    category: 'Logo Animation',
    technologies: ['After Effects', 'Cinema 4D'],
    links: {
      preview: 'https://tanvirvisuals.com',
      github: '',
      githubApi: '',
    },
  },
  {
    video: '/motion-3.mp4',
    title: 'Mega City Animation',
    description: 'Smooth user interface animation design',
    category: 'Promotional Ads',
    technologies: ['After Effects', 'Adobe XD'],
    links: {
      preview: 'https://tanvirvisuals.com',
      github: '',
      githubApi: '',
    },
  },
  {
    video: '/motion-4.mp4',
    title: 'Fashion Reel Animation',
    description: 'Engaging social media animation reel',
    category: 'Shorts/Reels',
    technologies: ['Premiere Pro', 'After Effects'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    video: '/motion-5.mp4',
    title: 'Logo Animation',
    description: 'Professional logo animation sequence',
    category: 'Logo Animation',
    technologies: ['After Effects', 'Cinema 4D'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
  {
    video: '/motion-6.mp4',
    title: 'Text Animation',
    description: 'Creative text animation with transitions',
    category: 'Video Editing',
    technologies: ['After Effects', 'Premiere Pro'],
    links: {
      preview: '#',
      github: '',
      githubApi: '',
    },
  },
] as const;

export const experiencesData = [
  {
    title: 'Creative Graphic Designer',
    company: 'Unifly Travels',
    description:
      'I have been working mostly as a static graphic designer with a focus on Adobe Illustrator, Photoshop, and InDesign. I have also had the opportunity to work with motion graphics, video editing, and website design. I am passionate about creating visually stunning and engaging content that tells a story and leaves a lasting impression.',
    period: '2023-2026',
    technologies: [
      'Adobe Illustrator',
      'Photoshop',
      'Premier Pro',
      'After Effects',
    ],
  },
  {
    title: 'Graphic Designer',
    company: 'Sys Computer Ltd.',
    description:
      'At Sys Computer Ltd., I was responsible for creating visually appealing graphics and designs to promote the company’s products and services. I collaborated with the marketing team to develop creative concepts and executed them using Adobe Illustrator and Photoshop. My work included designing social media posts, banners, flyers, and other promotional materials to enhance the company’s brand presence.',
    period: '2022 - 2023',
    technologies: ['Photoshop', 'Illustrator', 'Lightroom', 'Canva'],
  },
  {
    title: 'Graphic Designer',
    company: 'SYP Solutions Ltd.',
    description:
      'At SYP Solutions Ltd., I was responsible for creating visually appealing graphics and designs to promote the company’s products and services. I collaborated with the marketing team to develop creative concepts and executed them using Adobe Illustrator and Photoshop. My work included designing social media posts, banners, flyers, and other promotional materials to enhance the company’s brand presence.',
    period: '2020 - 2022',
    technologies: ['Photoshop', 'Illustrator', 'Lightroom', 'Canva'],
  },
] as const;

export const skillsData = [
  { icon: <Icons.html className="size-12" /> },
  { icon: <Icons.css className="size-12" /> },
  { icon: <Icons.sass className="size-12" /> },
  { icon: <Icons.tailwind className="size-12" /> },
  { icon: <Icons.javascript className="size-12" /> },
  { icon: <Icons.typescript className="size-12" /> },
  { icon: <Icons.react className="size-12" /> },
  { icon: <Icons.redux className="size-12" /> },
  { icon: <Icons.nextjs className="size-12" /> },
  { icon: <Icons.nestjs className="size-12" /> },
  { icon: <Icons.prisma className="size-12" /> },
  { icon: <Icons.docker className="size-12" /> },
] as const;

// Skills
export const skillsData2 = [
  {
    name: 'Photoshop',
    level: 95,
    icon: '/skills/photoshop.png',
  },
  {
    name: 'Illustrator',
    level: 90,
    icon: '/skills/illustrator.png',
  },
  {
    name: 'Premiere Pro',
    level: 90,
    icon: '/skills/premierepro.png',
  },
  {
    name: 'After Effects',
    level: 90,
    icon: '/skills/ae.png',
  },
  {
    name: 'MS Office',
    level: 90,
    icon: '/skills/msoffice.png',
  },
] as const;
